#include "ocio_lut_baker.h"

#include <QFile>
#include <QSaveFile>
#include <QTextStream>

namespace OCIO = OCIO_NAMESPACE;

namespace qcv::OcioLutBaker {

QString writeCube(OCIO::ConstCPUProcessorRcPtr proc,
                  const QString &outPath,
                  int cubeSize)
{
    if (!proc) {
        return QStringLiteral("OcioLutBaker: null CPU processor");
    }
    if (cubeSize < 2) {
        return QStringLiteral("OcioLutBaker: cubeSize must be ≥ 2");
    }
    if (outPath.isEmpty()) {
        return QStringLiteral("OcioLutBaker: empty output path");
    }

    // QSaveFile gives us atomic write — if the bake aborts mid-loop
    // (OCIO exception) the user's previous LUT file at the same path
    // isn't clobbered.
    QSaveFile file(outPath);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Text)) {
        return QStringLiteral("OcioLutBaker: cannot open '%1' for writing: %2")
                   .arg(outPath, file.errorString());
    }

    QTextStream out(&file);
    out.setRealNumberPrecision(6);
    out.setRealNumberNotation(QTextStream::FixedNotation);

    out << "# Generated by QCView Player\n"
        << "TITLE \"OCIO Transform LUT\"\n"
        << "\n"
        << "LUT_3D_SIZE " << cubeSize << "\n"
        << "\n"
        << "DOMAIN_MIN 0.0 0.0 0.0\n"
        << "DOMAIN_MAX 1.0 1.0 1.0\n"
        << "\n";

    // Iridas .cube convention: R varies fastest, then G, then B.
    const float step = 1.0f / static_cast<float>(cubeSize - 1);
    float rgb[3];

    try {
        for (int b = 0; b < cubeSize; ++b) {
            for (int g = 0; g < cubeSize; ++g) {
                for (int r = 0; r < cubeSize; ++r) {
                    rgb[0] = static_cast<float>(r) * step;
                    rgb[1] = static_cast<float>(g) * step;
                    rgb[2] = static_cast<float>(b) * step;
                    proc->applyRGB(rgb);
                    // Negative values are valid for HDR / extended-range
                    // chains (scene-linear can dip below zero through
                    // some looks); .cube readers tolerate them.
                    out << rgb[0] << ' ' << rgb[1] << ' ' << rgb[2] << '\n';
                }
            }
        }
    } catch (const OCIO::Exception &e) {
        file.cancelWriting();
        return QStringLiteral("OcioLutBaker: OCIO sampling failed: %1").arg(e.what());
    }

    out.flush();
    if (!file.commit()) {
        return QStringLiteral("OcioLutBaker: failed to commit '%1': %2")
                   .arg(outPath, file.errorString());
    }
    return {};
}

} // namespace qcv::OcioLutBaker
