#pragma once

// ============================================================================
// ICON DEFINITIONS (Material Design Symbols)
// ============================================================================
#define ICON_SKIP_PREVIOUS          u8"\uE045"
#define ICON_FAST_REWIND            u8"\uE020"
#define ICON_ARROW_LEFT             u8"\uE5CB"
#define ICON_PLAY_ARROW             u8"\uE037"
#define ICON_PAUSE                  u8"\uE034"
#define ICON_ARROW_RIGHT            u8"\uE5CC"
#define ICON_FAST_FORWARD           u8"\uE01F"
#define ICON_SKIP_NEXT              u8"\uE044"
#define ICON_FOLDER_OPEN            u8"\uE2C8"
#define ICON_CONTENT_COPY           u8"\xE14D"
#define ICON_CONTENT_CUT            u8"\uE14E"
#define ICON_ARTICLE                u8"\uEF42"
#define ICON_SCREENSHOT_CLIPBOARD   u8"\uF7d3"
#define ICON_SCREENSHOT_DESKTOP     u8"\uF727"
#define ICON_FULLSCREEN             u8"\uE5d0"
#define ICON_TONALITY               u8"\uE891"
#define ICON_MASK                   u8"\uE22F"
#define ICON_WINDOWS                u8"\uF7E4"
#define ICON_TIMECODE               u8"\uE8B5"
#define ICON_SPLIT_SCENE            u8"\uF3BF"
#define ICON_SPLIT_SCREEN_LEFT      u8"\uF675"
#define ICON_SPLIT_SCREEN_BOTTOM    u8"\uF676"
#define ICON_BACK                   u8"\uE5C4"
#define ICON_FORWARD                u8"\uE5C8"
#define ICON_VIEW_TIMELINE          u8"\uEB85"
#define ICON_FLOWCHART              u8"\uF38D"
#define ICON_CLOSE                  u8"\uE5CD"
#define ICON_HOURGLASS_EMPTY        u8"\uE88B"
#define ICON_DELETE                 u8"\uE872"
#define ICON_LIST                   u8"\uE896"
#define ICON_LOOP                   u8"\uE863"
#define ICON_LOOP_OFF               u8"\uF826"
#define ICON_SPEED                  u8"\ue9e4"
#define ICON_RES_FULL               u8"\ue3d3"
#define ICON_RES_HALF               u8"\ue3d1"
#define ICON_RES_QUARTER            u8"\ue3d4"
#define ICON_INFO                   u8"\ue88e"
#define ICON_LINK                   u8"\ue157"
#define ICON_HDR_ON                 u8"\ue3ee"
#define ICON_HDR_OFF                u8"\ue3ed"
#define ICON_VIDEOCAM               u8"\ue04b"
#define ICON_IMAGE                  u8"\uE3F4"
#define ICON_HIDE_IMAGE             u8"\uF022"
#define ICON_SCHEDULE               u8"\uE8B5"
#define ICON_FIRST_PAGE             u8"\uE5DC"
#define ICON_LAST_PAGE              u8"\uE5DD"

// EXR/Render Pass Icons
#define ICON_PALETTE                u8"\uE40A"
#define ICON_LIGHTBULB              u8"\uE8F4"
#define ICON_BRIGHTNESS_6           u8"\uE40C"
#define ICON_AUTO_AWESOME           u8"\uE65F"
#define ICON_LAYERS                 u8"\uE53B"
#define ICON_STRAIGHTEN             u8"\uE3E2"
#define ICON_SQUARE_FOOT            u8"\uEA04"
#define ICON_GRID_ON                u8"\uE90D"
#define ICON_VISIBILITY             u8"\uE8F4"
#define ICON_VISIBILITY_OFF         u8"\uE8F5"
#define ICON_VOLUME_UP              u8"\ue050"
#define ICON_VIDEO_LIBRARY          u8"\uEB87"
#define ICON_PLAYLIST_PLAY          u8"\ue05f"
#define ICON_COLOR_PROFILE_ENTRY    u8"\uF70C"
#define ICON_PLAY_CIRCLE            u8"\ue037"
#define ICON_AUDIO_TRACK            u8"\uE3A1"
#define ICON_MOVIE                  u8"\uE02C"
#define ICON_VOLUME_MUTE            u8"\uE04F"
#define ICON_MODEL_TRAINING         u8"\uF0CF"
#define ICON_DISPLAY_SETTINGS       u8"\uEB97"

// Annotation Drawing Icons
#define ICON_DRAW                   u8"\uE22B"
#define ICON_RECTANGLE              u8"\ueb36"
#define ICON_CIRCLE                 u8"\uEF4A"
#define ICON_ARROW_FORWARD          u8"\uE5C8"
#define ICON_REMOVE                 u8"\uE15B"
#define ICON_UNDO                   u8"\uE166"
#define ICON_REDO                   u8"\uE15A"
#define ICON_CHECK                  u8"\uE5CA"
#define ICON_CANCEL                 u8"\uE5C9"
#define ICON_LABEL                  u8"\uE892"
#define ICON_LABEL_IMPORTANT        u8"\uE937"
#define ICON_UNDO_ALT               u8"\uE166"
#define ICON_DELETE_SWEEP           u8"\uE16C"
#define ICON_PALETTE_COLOR          u8"\uE40A"
#define ICON_INPUT_SETTINGS         u8"\uE8C0"
#define ICON_GRID_VIEW              u8"\uE9B0"
#define ICON_HOME_MAX               u8"\uF024"
#define ICON_BACKGROUND             u8"\uF20A"
#define ICON_NOTE_STACK             u8"\uF562"
#define ICON_CLOSE_LARGE            u8"\uE5CD"
#define ICON_WARNING                u8"\uE002"
#define ICON_DONE                   u8"\uE876"
#define ICON_ARROW_DROP_DOWN        u8"\uE5C7"
#define ICON_STACKED_LINE_CHART     u8"\uF22B"
#define ICON_REFRESH                u8"\uE5D5"
#define ICON_TIMELAPSE              u8"\uE91B"

// Sidebar panel icons
#define ICON_TOPIC                  u8"\uEB13"
#define ICON_INFO_OUTLINE           u8"\uE88F"
#define ICON_VIEW_AGENDA            u8"\uE8E9"
#define ICON_BRUSH                  u8"\uE3AE"

// Sidebar file action icons
#define ICON_FOLDER                 u8"\uE2C7"
#define ICON_FOLDER_SPECIAL         u8"\uE70E"
#define ICON_COLOR_PRESETS          u8"\uE6D4"
#define ICON_COLOR_PROFILES         u8"\uE3DB"
#define ICON_SAVE                   u8"\uE161"
